### ISSUE TITLE
Not working csv upload after refresh

### ISSUE THREAD

**Issue by drigani** [noitcudni/google-webmaster-tools-bulk-url-removal#101]
I have a csv of urls in the format as requested. Just the urls in column 1. Go to search console, go to removals, hit the green upload icon, select the csv and nothing happens. I refresh the page and same thing.

Ideas? Using the extension on linux mint 19, Chrome Version 86.0.4240.198 (Official Build) (64-bit)64-bit). 
Have restarted Chrome and no luck and installed Re enabled extension managment

**Comment by noitcudni** [comment]
On linux when you click on the submit button and select the csv file, you'll notice that the extension goes away immediately. That's the root of the problem. It needs to stay up for at least a little while in order to finish parsing and forwarding the csv data to the background.

Here's my workaround. 
1. Click on the extension popup.
2. Right click on the popup and select inspect to bring up the developer console.
3. Proceed as normal. You should see that now your popup stays up.
