### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by corvettesalvage** [noitcudni/google-webmaster-tools-bulk-url-removal#18]
I paid for the extension in the google chrome store and the extension automatically loaded in the chrome browser. When I click the extension icon it keeps bringing me back to extensions page and says the extension is installed and says its added to chrome but will not allow me to use the extension

![screen shot 2018-08-10 at 9 58 12 am](https://user-images.githubusercontent.com/42275564/43965125-17ce62fc-9c84-11e8-8408-e0db69fc441b.png)

**Comment by noitcudni** [comment]
The extension button doesn't do anything. However, I probably should make it so that it either directs you to the right page directly or tells you where to go.

Go to your webmaster tools. Click on Google Index-> Removel URL. Click on Choose file to select your csv file.

See https://github.com/noitcudni/google-webmaster-tools-bulk-url-removal/blob/master/README.md for instructions.

**Comment by ano2233** [comment]
what is the exact link where this extension can be used to upload the file ?
there is no link from the readme...
