### ISSUE TITLE
Bulk URL removal tool error not automatic

### ISSUE THREAD

**Issue by josepbbs** [noitcudni/google-webmaster-tools-bulk-url-removal#45]
hi there,

I have been using the tool for several months and from night to following day I upload the target csv file and only detects the first URL and I have to push the "Send" button every time one per one
Automatic function has been deactivated, I did not add any new extension, I tested in Windows and in Mac OS,
I guess Chrome updated itself automatically to the last version and now the automatic function does not work

Any ideas please?
thanks in advance

**Comment by noitcudni** [comment]
Can you send me your CSV file?

**Comment by noitcudni** [comment]
Yup, I did introduce a bug in the later version. My apologies. I'm fixing it now.

**Comment by noitcudni** [comment]
Please try 0.15. 0.14 was broken for non-English users. 

The crux of the problem is that I need to parse out google webmaster tools' messages to decide how to proceed. While it works fine in English, in Spanish it had an extra comma. So, now I'm parsing the content of `innerHTML`, which should solve this issue.

On a related note, the extension also skips over URLs that have already been submitted should google webmaster complain about duplicate submission. Once again I need to parse the human-readable message coming from the webmaster tools. It's essentially a string match. As a result, skipping over already submitted will break for non-English users. The best way to get around this is to set your language settings to English by changing webmaster's url `hl` parameter to `en`.
For example,
`hl=en`

I'm thinking that I'll alert people ahead of time about the language issue and present an option to switch to English more readily.

**Comment by josepbbs** [comment]
Now it works !!! 
;-) Superb 
thank you for your support

**Comment by josepbbs** [comment]
Seems working now...

**Comment by noitcudni** [comment]
Yes, email me your csv file. Also, can you describe how it does work? For
example, what are you seeing on the screen? Is it erroring out 500, etc.

Lih
